// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/cosmos.upgrade.v1beta1/module'
import { unref } from 'vue'

import useIgnite from '../use'

type QueryCurrentPlanType = typeof Module.prototype.queryCurrentPlan
type QueryAppliedPlanType = typeof Module.prototype.queryAppliedPlan
type QueryUpgradedConsensusStateType =
  typeof Module.prototype.queryUpgradedConsensusState
type QueryModuleVersionsType = typeof Module.prototype.queryModuleVersions

type Response = {
  queryCurrentPlan: QueryCurrentPlanType
  queryAppliedPlan: QueryAppliedPlanType
  queryUpgradedConsensusState: QueryUpgradedConsensusStateType
  queryModuleVersions: QueryModuleVersionsType
}

function useModule(): Response {
  let { ignite } = useIgnite()

  let {
    queryCurrentPlan,

    queryAppliedPlan,

    queryUpgradedConsensusState,

    queryModuleVersions
  } = unref(ignite.cosmosUpgradeV1Beta1)

  queryCurrentPlan = queryCurrentPlan.bind(ignite.cosmosUpgradeV1Beta1)

  queryAppliedPlan = queryAppliedPlan.bind(ignite.cosmosUpgradeV1Beta1)

  queryUpgradedConsensusState = queryUpgradedConsensusState.bind(
    ignite.cosmosUpgradeV1Beta1
  )

  queryModuleVersions = queryModuleVersions.bind(ignite.cosmosUpgradeV1Beta1)

  return {
    queryCurrentPlan,

    queryAppliedPlan,

    queryUpgradedConsensusState,

    queryModuleVersions
  }
}

export { useModule }
