// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.gov.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgSubmitProposalType = typeof Module.prototype.sendMsgSubmitProposal
type SendMsgVoteWeightedType = typeof Module.prototype.sendMsgVoteWeighted
type SendMsgDepositType = typeof Module.prototype.sendMsgDeposit
type SendMsgVoteType = typeof Module.prototype.sendMsgVote

type QueryProposalType = typeof Module.prototype.queryProposal
type QueryProposalsType = typeof Module.prototype.queryProposals
type QueryVoteType = typeof Module.prototype.queryVote
type QueryVotesType = typeof Module.prototype.queryVotes
type QueryParamsType = typeof Module.prototype.queryParams
type QueryDepositType = typeof Module.prototype.queryDeposit
type QueryDepositsType = typeof Module.prototype.queryDeposits
type QueryTallyResultType = typeof Module.prototype.queryTallyResult

type Response = {
  sendMsgSubmitProposal: SendMsgSubmitProposalType
  sendMsgVoteWeighted: SendMsgVoteWeightedType
  sendMsgDeposit: SendMsgDepositType
  sendMsgVote: SendMsgVoteType

  queryProposal: QueryProposalType
  queryProposals: QueryProposalsType
  queryVote: QueryVoteType
  queryVotes: QueryVotesType
  queryParams: QueryParamsType
  queryDeposit: QueryDepositType
  queryDeposits: QueryDepositsType
  queryTallyResult: QueryTallyResultType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    sendMsgSubmitProposal,

    sendMsgVoteWeighted,

    sendMsgDeposit,

    sendMsgVote,

    queryProposal,

    queryProposals,

    queryVote,

    queryVotes,

    queryParams,

    queryDeposit,

    queryDeposits,

    queryTallyResult
  } = unref(gaia.cosmosGovV1Beta1)

  sendMsgSubmitProposal = sendMsgSubmitProposal.bind(gaia.cosmosGovV1Beta1)

  sendMsgVoteWeighted = sendMsgVoteWeighted.bind(gaia.cosmosGovV1Beta1)

  sendMsgDeposit = sendMsgDeposit.bind(gaia.cosmosGovV1Beta1)

  sendMsgVote = sendMsgVote.bind(gaia.cosmosGovV1Beta1)

  queryProposal = queryProposal.bind(gaia.cosmosGovV1Beta1)

  queryProposals = queryProposals.bind(gaia.cosmosGovV1Beta1)

  queryVote = queryVote.bind(gaia.cosmosGovV1Beta1)

  queryVotes = queryVotes.bind(gaia.cosmosGovV1Beta1)

  queryParams = queryParams.bind(gaia.cosmosGovV1Beta1)

  queryDeposit = queryDeposit.bind(gaia.cosmosGovV1Beta1)

  queryDeposits = queryDeposits.bind(gaia.cosmosGovV1Beta1)

  queryTallyResult = queryTallyResult.bind(gaia.cosmosGovV1Beta1)

  return {
    sendMsgSubmitProposal,

    sendMsgVoteWeighted,

    sendMsgDeposit,

    sendMsgVote,

    queryProposal,

    queryProposals,

    queryVote,

    queryVotes,

    queryParams,

    queryDeposit,

    queryDeposits,

    queryTallyResult
  }
}

export { useModule }
