// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.distribution.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgWithdrawValidatorCommissionType =
  typeof Module.prototype.sendMsgWithdrawValidatorCommission
type SendMsgWithdrawDelegatorRewardType =
  typeof Module.prototype.sendMsgWithdrawDelegatorReward
type SendMsgSetWithdrawAddressType =
  typeof Module.prototype.sendMsgSetWithdrawAddress
type SendMsgFundCommunityPoolType =
  typeof Module.prototype.sendMsgFundCommunityPool

type QueryParamsType = typeof Module.prototype.queryParams
type QueryValidatorOutstandingRewardsType =
  typeof Module.prototype.queryValidatorOutstandingRewards
type QueryValidatorCommissionType =
  typeof Module.prototype.queryValidatorCommission
type QueryValidatorSlashesType = typeof Module.prototype.queryValidatorSlashes
type QueryDelegationRewardsType = typeof Module.prototype.queryDelegationRewards
type QueryDelegationTotalRewardsType =
  typeof Module.prototype.queryDelegationTotalRewards
type QueryDelegatorValidatorsType =
  typeof Module.prototype.queryDelegatorValidators
type QueryDelegatorWithdrawAddressType =
  typeof Module.prototype.queryDelegatorWithdrawAddress
type QueryCommunityPoolType = typeof Module.prototype.queryCommunityPool

type Response = {
  sendMsgWithdrawValidatorCommission: SendMsgWithdrawValidatorCommissionType
  sendMsgWithdrawDelegatorReward: SendMsgWithdrawDelegatorRewardType
  sendMsgSetWithdrawAddress: SendMsgSetWithdrawAddressType
  sendMsgFundCommunityPool: SendMsgFundCommunityPoolType

  queryParams: QueryParamsType
  queryValidatorOutstandingRewards: QueryValidatorOutstandingRewardsType
  queryValidatorCommission: QueryValidatorCommissionType
  queryValidatorSlashes: QueryValidatorSlashesType
  queryDelegationRewards: QueryDelegationRewardsType
  queryDelegationTotalRewards: QueryDelegationTotalRewardsType
  queryDelegatorValidators: QueryDelegatorValidatorsType
  queryDelegatorWithdrawAddress: QueryDelegatorWithdrawAddressType
  queryCommunityPool: QueryCommunityPoolType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    sendMsgWithdrawValidatorCommission,

    sendMsgWithdrawDelegatorReward,

    sendMsgSetWithdrawAddress,

    sendMsgFundCommunityPool,

    queryParams,

    queryValidatorOutstandingRewards,

    queryValidatorCommission,

    queryValidatorSlashes,

    queryDelegationRewards,

    queryDelegationTotalRewards,

    queryDelegatorValidators,

    queryDelegatorWithdrawAddress,

    queryCommunityPool
  } = unref(gaia.cosmosDistributionV1Beta1)

  sendMsgWithdrawValidatorCommission = sendMsgWithdrawValidatorCommission.bind(
    gaia.cosmosDistributionV1Beta1
  )

  sendMsgWithdrawDelegatorReward = sendMsgWithdrawDelegatorReward.bind(
    gaia.cosmosDistributionV1Beta1
  )

  sendMsgSetWithdrawAddress = sendMsgSetWithdrawAddress.bind(
    gaia.cosmosDistributionV1Beta1
  )

  sendMsgFundCommunityPool = sendMsgFundCommunityPool.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryParams = queryParams.bind(gaia.cosmosDistributionV1Beta1)

  queryValidatorOutstandingRewards = queryValidatorOutstandingRewards.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryValidatorCommission = queryValidatorCommission.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryValidatorSlashes = queryValidatorSlashes.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryDelegationRewards = queryDelegationRewards.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryDelegationTotalRewards = queryDelegationTotalRewards.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryDelegatorValidators = queryDelegatorValidators.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryDelegatorWithdrawAddress = queryDelegatorWithdrawAddress.bind(
    gaia.cosmosDistributionV1Beta1
  )

  queryCommunityPool = queryCommunityPool.bind(gaia.cosmosDistributionV1Beta1)

  return {
    sendMsgWithdrawValidatorCommission,

    sendMsgWithdrawDelegatorReward,

    sendMsgSetWithdrawAddress,

    sendMsgFundCommunityPool,

    queryParams,

    queryValidatorOutstandingRewards,

    queryValidatorCommission,

    queryValidatorSlashes,

    queryDelegationRewards,

    queryDelegationTotalRewards,

    queryDelegatorValidators,

    queryDelegatorWithdrawAddress,

    queryCommunityPool
  }
}

export { useModule }
