// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.staking.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgDelegateType = typeof Module.prototype.sendMsgDelegate
type SendMsgCreateValidatorType = typeof Module.prototype.sendMsgCreateValidator
type SendMsgEditValidatorType = typeof Module.prototype.sendMsgEditValidator
type SendMsgBeginRedelegateType = typeof Module.prototype.sendMsgBeginRedelegate
type SendMsgUndelegateType = typeof Module.prototype.sendMsgUndelegate

type QueryValidatorsType = typeof Module.prototype.queryValidators
type QueryValidatorType = typeof Module.prototype.queryValidator
type QueryValidatorDelegationsType =
  typeof Module.prototype.queryValidatorDelegations
type QueryValidatorUnbondingDelegationsType =
  typeof Module.prototype.queryValidatorUnbondingDelegations
type QueryDelegationType = typeof Module.prototype.queryDelegation
type QueryUnbondingDelegationType =
  typeof Module.prototype.queryUnbondingDelegation
type QueryDelegatorDelegationsType =
  typeof Module.prototype.queryDelegatorDelegations
type QueryDelegatorUnbondingDelegationsType =
  typeof Module.prototype.queryDelegatorUnbondingDelegations
type QueryRedelegationsType = typeof Module.prototype.queryRedelegations
type QueryDelegatorValidatorsType =
  typeof Module.prototype.queryDelegatorValidators
type QueryDelegatorValidatorType =
  typeof Module.prototype.queryDelegatorValidator
type QueryHistoricalInfoType = typeof Module.prototype.queryHistoricalInfo
type QueryPoolType = typeof Module.prototype.queryPool
type QueryParamsType = typeof Module.prototype.queryParams

type Response = {
  sendMsgDelegate: SendMsgDelegateType
  sendMsgCreateValidator: SendMsgCreateValidatorType
  sendMsgEditValidator: SendMsgEditValidatorType
  sendMsgBeginRedelegate: SendMsgBeginRedelegateType
  sendMsgUndelegate: SendMsgUndelegateType

  queryValidators: QueryValidatorsType
  queryValidator: QueryValidatorType
  queryValidatorDelegations: QueryValidatorDelegationsType
  queryValidatorUnbondingDelegations: QueryValidatorUnbondingDelegationsType
  queryDelegation: QueryDelegationType
  queryUnbondingDelegation: QueryUnbondingDelegationType
  queryDelegatorDelegations: QueryDelegatorDelegationsType
  queryDelegatorUnbondingDelegations: QueryDelegatorUnbondingDelegationsType
  queryRedelegations: QueryRedelegationsType
  queryDelegatorValidators: QueryDelegatorValidatorsType
  queryDelegatorValidator: QueryDelegatorValidatorType
  queryHistoricalInfo: QueryHistoricalInfoType
  queryPool: QueryPoolType
  queryParams: QueryParamsType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    sendMsgDelegate,

    sendMsgCreateValidator,

    sendMsgEditValidator,

    sendMsgBeginRedelegate,

    sendMsgUndelegate,

    queryValidators,

    queryValidator,

    queryValidatorDelegations,

    queryValidatorUnbondingDelegations,

    queryDelegation,

    queryUnbondingDelegation,

    queryDelegatorDelegations,

    queryDelegatorUnbondingDelegations,

    queryRedelegations,

    queryDelegatorValidators,

    queryDelegatorValidator,

    queryHistoricalInfo,

    queryPool,

    queryParams
  } = unref(gaia.cosmosStakingV1Beta1)

  sendMsgDelegate = sendMsgDelegate.bind(gaia.cosmosStakingV1Beta1)

  sendMsgCreateValidator = sendMsgCreateValidator.bind(
    gaia.cosmosStakingV1Beta1
  )

  sendMsgEditValidator = sendMsgEditValidator.bind(gaia.cosmosStakingV1Beta1)

  sendMsgBeginRedelegate = sendMsgBeginRedelegate.bind(
    gaia.cosmosStakingV1Beta1
  )

  sendMsgUndelegate = sendMsgUndelegate.bind(gaia.cosmosStakingV1Beta1)

  queryValidators = queryValidators.bind(gaia.cosmosStakingV1Beta1)

  queryValidator = queryValidator.bind(gaia.cosmosStakingV1Beta1)

  queryValidatorDelegations = queryValidatorDelegations.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryValidatorUnbondingDelegations = queryValidatorUnbondingDelegations.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryDelegation = queryDelegation.bind(gaia.cosmosStakingV1Beta1)

  queryUnbondingDelegation = queryUnbondingDelegation.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryDelegatorDelegations = queryDelegatorDelegations.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryDelegatorUnbondingDelegations = queryDelegatorUnbondingDelegations.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryRedelegations = queryRedelegations.bind(gaia.cosmosStakingV1Beta1)

  queryDelegatorValidators = queryDelegatorValidators.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryDelegatorValidator = queryDelegatorValidator.bind(
    gaia.cosmosStakingV1Beta1
  )

  queryHistoricalInfo = queryHistoricalInfo.bind(gaia.cosmosStakingV1Beta1)

  queryPool = queryPool.bind(gaia.cosmosStakingV1Beta1)

  queryParams = queryParams.bind(gaia.cosmosStakingV1Beta1)

  return {
    sendMsgDelegate,

    sendMsgCreateValidator,

    sendMsgEditValidator,

    sendMsgBeginRedelegate,

    sendMsgUndelegate,

    queryValidators,

    queryValidator,

    queryValidatorDelegations,

    queryValidatorUnbondingDelegations,

    queryDelegation,

    queryUnbondingDelegation,

    queryDelegatorDelegations,

    queryDelegatorUnbondingDelegations,

    queryRedelegations,

    queryDelegatorValidators,

    queryDelegatorValidator,

    queryHistoricalInfo,

    queryPool,

    queryParams
  }
}

export { useModule }
