// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.bank.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgMultiSendType = typeof Module.prototype.sendMsgMultiSend
type SendMsgSendType = typeof Module.prototype.sendMsgSend

type QueryBalanceType = typeof Module.prototype.queryBalance
type QueryAllBalancesType = typeof Module.prototype.queryAllBalances
type QuerySpendableBalancesType = typeof Module.prototype.querySpendableBalances
type QueryTotalSupplyType = typeof Module.prototype.queryTotalSupply
type QuerySupplyOfType = typeof Module.prototype.querySupplyOf
type QueryParamsType = typeof Module.prototype.queryParams
type QueryDenomMetadataType = typeof Module.prototype.queryDenomMetadata
type QueryDenomsMetadataType = typeof Module.prototype.queryDenomsMetadata

type Response = {
  sendMsgMultiSend: SendMsgMultiSendType
  sendMsgSend: SendMsgSendType

  queryBalance: QueryBalanceType
  queryAllBalances: QueryAllBalancesType
  querySpendableBalances: QuerySpendableBalancesType
  queryTotalSupply: QueryTotalSupplyType
  querySupplyOf: QuerySupplyOfType
  queryParams: QueryParamsType
  queryDenomMetadata: QueryDenomMetadataType
  queryDenomsMetadata: QueryDenomsMetadataType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    sendMsgMultiSend,

    sendMsgSend,

    queryBalance,

    queryAllBalances,

    querySpendableBalances,

    queryTotalSupply,

    querySupplyOf,

    queryParams,

    queryDenomMetadata,

    queryDenomsMetadata
  } = unref(gaia.cosmosBankV1Beta1)

  sendMsgMultiSend = sendMsgMultiSend.bind(gaia.cosmosBankV1Beta1)

  sendMsgSend = sendMsgSend.bind(gaia.cosmosBankV1Beta1)

  queryBalance = queryBalance.bind(gaia.cosmosBankV1Beta1)

  queryAllBalances = queryAllBalances.bind(gaia.cosmosBankV1Beta1)

  querySpendableBalances = querySpendableBalances.bind(gaia.cosmosBankV1Beta1)

  queryTotalSupply = queryTotalSupply.bind(gaia.cosmosBankV1Beta1)

  querySupplyOf = querySupplyOf.bind(gaia.cosmosBankV1Beta1)

  queryParams = queryParams.bind(gaia.cosmosBankV1Beta1)

  queryDenomMetadata = queryDenomMetadata.bind(gaia.cosmosBankV1Beta1)

  queryDenomsMetadata = queryDenomsMetadata.bind(gaia.cosmosBankV1Beta1)

  return {
    sendMsgMultiSend,

    sendMsgSend,

    queryBalance,

    queryAllBalances,

    querySpendableBalances,

    queryTotalSupply,

    querySupplyOf,

    queryParams,

    queryDenomMetadata,

    queryDenomsMetadata
  }
}

export { useModule }
