// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/tendermint.spn.monitoringp/module'
import { unref } from 'vue'

import useIgnite from '../use'

type QueryConsumerClientIDType = typeof Module.prototype.queryConsumerClientID
type QueryConnectionChannelIDType =
  typeof Module.prototype.queryConnectionChannelID
type QueryMonitoringInfoType = typeof Module.prototype.queryMonitoringInfo
type QueryParamsType = typeof Module.prototype.queryParams

type Response = {
  queryConsumerClientID: QueryConsumerClientIDType
  queryConnectionChannelID: QueryConnectionChannelIDType
  queryMonitoringInfo: QueryMonitoringInfoType
  queryParams: QueryParamsType
}

function useModule(): Response {
  let { ignite } = useIgnite()

  let {
    queryConsumerClientID,

    queryConnectionChannelID,

    queryMonitoringInfo,

    queryParams
  } = unref(ignite.tendermintSpnMonitoringp)

  queryConsumerClientID = queryConsumerClientID.bind(
    ignite.tendermintSpnMonitoringp
  )

  queryConnectionChannelID = queryConnectionChannelID.bind(
    ignite.tendermintSpnMonitoringp
  )

  queryMonitoringInfo = queryMonitoringInfo.bind(
    ignite.tendermintSpnMonitoringp
  )

  queryParams = queryParams.bind(ignite.tendermintSpnMonitoringp)

  return {
    queryConsumerClientID,

    queryConnectionChannelID,

    queryMonitoringInfo,

    queryParams
  }
}

export { useModule }
