// Generated by Ignite ignite.com/cli

import { StdFee } from '@cosmjs/launchpad'
import { EncodeObject } from '@cosmjs/proto-signing'
import { DeliverTxResponse, SigningStargateClient } from '@cosmjs/stargate'

import { Api } from './rest'
import { MsgRevoke } from './types/cosmos/authz/v1beta1/tx'
import { MsgGrant } from './types/cosmos/authz/v1beta1/tx'
import { MsgExec } from './types/cosmos/authz/v1beta1/tx'

type sendMsgRevokeParams = {
  value: MsgRevoke
  fee?: StdFee
  memo?: string
}

type sendMsgGrantParams = {
  value: MsgGrant
  fee?: StdFee
  memo?: string
}

type sendMsgExecParams = {
  value: MsgExec
  fee?: StdFee
  memo?: string
}

type msgRevokeParams = {
  value: MsgRevoke
}

type msgGrantParams = {
  value: MsgGrant
}

type msgExecParams = {
  value: MsgExec
}

class Module extends Api<any> {
  private _client: SigningStargateClient
  private _addr: string

  constructor(baseUrl: string) {
    super({
      baseUrl
    })
  }

  public withSigner(client: SigningStargateClient, _addr: string) {
    this._client = client
    this._addr = _addr
  }

  public noSigner() {
    this._client = undefined
    this._addr = undefined
  }

  async sendMsgRevoke({
    value,
    fee,
    memo
  }: sendMsgRevokeParams): Promise<DeliverTxResponse> {
    if (!this._client) {
      throw new Error(
        'TxClient:sendMsgRevoke: Unable to sign Tx. Signer is not present.'
      )
    }
    if (!this._addr) {
      throw new Error(
        'TxClient:sendMsgRevoke: Unable to sign Tx. Address is not present.'
      )
    }
    try {
      let msg = this.msgRevoke({ value: MsgRevoke.fromPartial(value) })
      return await this._client.signAndBroadcast(
        this._addr,
        [msg],
        fee ? fee : { amount: [], gas: '200000' },
        memo
      )
    } catch (e: any) {
      throw new Error(
        'TxClient:sendMsgRevoke: Could not broadcast Tx: ' + e.message
      )
    }
  }

  async sendMsgGrant({
    value,
    fee,
    memo
  }: sendMsgGrantParams): Promise<DeliverTxResponse> {
    if (!this._client) {
      throw new Error(
        'TxClient:sendMsgGrant: Unable to sign Tx. Signer is not present.'
      )
    }
    if (!this._addr) {
      throw new Error(
        'TxClient:sendMsgGrant: Unable to sign Tx. Address is not present.'
      )
    }
    try {
      let msg = this.msgGrant({ value: MsgGrant.fromPartial(value) })
      return await this._client.signAndBroadcast(
        this._addr,
        [msg],
        fee ? fee : { amount: [], gas: '200000' },
        memo
      )
    } catch (e: any) {
      throw new Error(
        'TxClient:sendMsgGrant: Could not broadcast Tx: ' + e.message
      )
    }
  }

  async sendMsgExec({
    value,
    fee,
    memo
  }: sendMsgExecParams): Promise<DeliverTxResponse> {
    if (!this._client) {
      throw new Error(
        'TxClient:sendMsgExec: Unable to sign Tx. Signer is not present.'
      )
    }
    if (!this._addr) {
      throw new Error(
        'TxClient:sendMsgExec: Unable to sign Tx. Address is not present.'
      )
    }
    try {
      let msg = this.msgExec({ value: MsgExec.fromPartial(value) })
      return await this._client.signAndBroadcast(
        this._addr,
        [msg],
        fee ? fee : { amount: [], gas: '200000' },
        memo
      )
    } catch (e: any) {
      throw new Error(
        'TxClient:sendMsgExec: Could not broadcast Tx: ' + e.message
      )
    }
  }

  msgRevoke({ value }: msgRevokeParams): EncodeObject {
    try {
      return {
        typeUrl: '/cosmos.authz.v1beta1.MsgRevoke',
        value: MsgRevoke.fromPartial(value)
      }
    } catch (e: any) {
      throw new Error(
        'TxClient:MsgRevoke: Could not create message: ' + e.message
      )
    }
  }

  msgGrant({ value }: msgGrantParams): EncodeObject {
    try {
      return {
        typeUrl: '/cosmos.authz.v1beta1.MsgGrant',
        value: MsgGrant.fromPartial(value)
      }
    } catch (e: any) {
      throw new Error(
        'TxClient:MsgGrant: Could not create message: ' + e.message
      )
    }
  }

  msgExec({ value }: msgExecParams): EncodeObject {
    try {
      return {
        typeUrl: '/cosmos.authz.v1beta1.MsgExec',
        value: MsgExec.fromPartial(value)
      }
    } catch (e: any) {
      throw new Error(
        'TxClient:MsgExec: Could not create message: ' + e.message
      )
    }
  }
}

export default Module
