// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.upgrade.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type QueryCurrentPlanType = typeof Module.prototype.queryCurrentPlan
type QueryAppliedPlanType = typeof Module.prototype.queryAppliedPlan
type QueryUpgradedConsensusStateType =
  typeof Module.prototype.queryUpgradedConsensusState
type QueryModuleVersionsType = typeof Module.prototype.queryModuleVersions

type Response = {
  queryCurrentPlan: QueryCurrentPlanType
  queryAppliedPlan: QueryAppliedPlanType
  queryUpgradedConsensusState: QueryUpgradedConsensusStateType
  queryModuleVersions: QueryModuleVersionsType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    queryCurrentPlan,

    queryAppliedPlan,

    queryUpgradedConsensusState,

    queryModuleVersions
  } = unref(gaia.cosmosUpgradeV1Beta1)

  queryCurrentPlan = queryCurrentPlan.bind(gaia.cosmosUpgradeV1Beta1)

  queryAppliedPlan = queryAppliedPlan.bind(gaia.cosmosUpgradeV1Beta1)

  queryUpgradedConsensusState = queryUpgradedConsensusState.bind(
    gaia.cosmosUpgradeV1Beta1
  )

  queryModuleVersions = queryModuleVersions.bind(gaia.cosmosUpgradeV1Beta1)

  return {
    queryCurrentPlan,

    queryAppliedPlan,

    queryUpgradedConsensusState,

    queryModuleVersions
  }
}

export { useModule }
