// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/cosmos.vesting.v1beta1/module'
import { unref } from 'vue'

import useIgnite from '../use'

type SendMsgCreateVestingAccountType =
  typeof Module.prototype.sendMsgCreateVestingAccount

type Response = {
  sendMsgCreateVestingAccount: SendMsgCreateVestingAccountType
}

function useModule(): Response {
  let { ignite } = useIgnite()

  let { sendMsgCreateVestingAccount } = unref(ignite.cosmosVestingV1Beta1)

  sendMsgCreateVestingAccount = sendMsgCreateVestingAccount.bind(
    ignite.cosmosVestingV1Beta1
  )

  return {
    sendMsgCreateVestingAccount
  }
}

export { useModule }
