// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.crisis.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgVerifyInvariantType = typeof Module.prototype.sendMsgVerifyInvariant

type Response = {
  sendMsgVerifyInvariant: SendMsgVerifyInvariantType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let { sendMsgVerifyInvariant } = unref(gaia.cosmosCrisisV1Beta1)

  sendMsgVerifyInvariant = sendMsgVerifyInvariant.bind(gaia.cosmosCrisisV1Beta1)

  return {
    sendMsgVerifyInvariant
  }
}

export { useModule }
