// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.params.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type QueryParamsType = typeof Module.prototype.queryParams

type Response = {
  queryParams: QueryParamsType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let { queryParams } = unref(gaia.cosmosParamsV1Beta1)

  queryParams = queryParams.bind(gaia.cosmosParamsV1Beta1)

  return {
    queryParams
  }
}

export { useModule }
