// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/cosmos.params.v1beta1/module'
import { unref } from 'vue'

import useIgnite from '../use'

type QueryParamsType = typeof Module.prototype.queryParams

type Response = {
  queryParams: QueryParamsType
}

function useModule(): Response {
  let { ignite } = useIgnite()

  let { queryParams } = unref(ignite.cosmosParamsV1Beta1)

  queryParams = queryParams.bind(ignite.cosmosParamsV1Beta1)

  return {
    queryParams
  }
}

export { useModule }
