// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/ibc.core.port.v1/module'
import { unref } from 'vue'

import useIgnite from '../use'

type Response = {}

function useModule(): Response {
  let { ignite } = useIgnite()

  let {} = unref(ignite.ibcCorePortV1)

  return {}
}

export { useModule }
