// Generated by Ignite ignite.com/cli
import Module from 'ignite-ts-client/ibc.applications.transfer.v1/module'
import { unref } from 'vue'

import useIgnite from '../use'

type SendMsgTransferType = typeof Module.prototype.sendMsgTransfer

type QueryDenomTraceType = typeof Module.prototype.queryDenomTrace
type QueryDenomTracesType = typeof Module.prototype.queryDenomTraces
type QueryParamsType = typeof Module.prototype.queryParams

type Response = {
  sendMsgTransfer: SendMsgTransferType

  queryDenomTrace: QueryDenomTraceType
  queryDenomTraces: QueryDenomTracesType
  queryParams: QueryParamsType
}

function useModule(): Response {
  let { ignite } = useIgnite()

  let {
    sendMsgTransfer,

    queryDenomTrace,

    queryDenomTraces,

    queryParams
  } = unref(ignite.ibcApplicationsTransferV1)

  sendMsgTransfer = sendMsgTransfer.bind(ignite.ibcApplicationsTransferV1)

  queryDenomTrace = queryDenomTrace.bind(ignite.ibcApplicationsTransferV1)

  queryDenomTraces = queryDenomTraces.bind(ignite.ibcApplicationsTransferV1)

  queryParams = queryParams.bind(ignite.ibcApplicationsTransferV1)

  return {
    sendMsgTransfer,

    queryDenomTrace,

    queryDenomTraces,

    queryParams
  }
}

export { useModule }
