// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/cosmos.vesting.v1beta1/module'
import { unref } from 'vue'

import useGaia from '../use'

type SendMsgCreateVestingAccountType =
  typeof Module.prototype.sendMsgCreateVestingAccount

type Response = {
  sendMsgCreateVestingAccount: SendMsgCreateVestingAccountType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let { sendMsgCreateVestingAccount } = unref(gaia.cosmosVestingV1Beta1)

  sendMsgCreateVestingAccount = sendMsgCreateVestingAccount.bind(
    gaia.cosmosVestingV1Beta1
  )

  return {
    sendMsgCreateVestingAccount
  }
}

export { useModule }
