// Generated by Ignite ignite.com/cli
import Module from 'cosmos-gaia-ts-client/ibc.core.connection.v1/module'
import { unref } from 'vue'

import useGaia from '../use'

type QueryConnectionType = typeof Module.prototype.queryConnection
type QueryConnectionsType = typeof Module.prototype.queryConnections
type QueryClientConnectionsType = typeof Module.prototype.queryClientConnections
type QueryConnectionClientStateType =
  typeof Module.prototype.queryConnectionClientState
type QueryConnectionConsensusStateType =
  typeof Module.prototype.queryConnectionConsensusState

type Response = {
  queryConnection: QueryConnectionType
  queryConnections: QueryConnectionsType
  queryClientConnections: QueryClientConnectionsType
  queryConnectionClientState: QueryConnectionClientStateType
  queryConnectionConsensusState: QueryConnectionConsensusStateType
}

function useModule(): Response {
  let { gaia } = useGaia()

  let {
    queryConnection,

    queryConnections,

    queryClientConnections,

    queryConnectionClientState,

    queryConnectionConsensusState
  } = unref(gaia.ibcCoreConnectionV1)

  queryConnection = queryConnection.bind(gaia.ibcCoreConnectionV1)

  queryConnections = queryConnections.bind(gaia.ibcCoreConnectionV1)

  queryClientConnections = queryClientConnections.bind(gaia.ibcCoreConnectionV1)

  queryConnectionClientState = queryConnectionClientState.bind(
    gaia.ibcCoreConnectionV1
  )

  queryConnectionConsensusState = queryConnectionConsensusState.bind(
    gaia.ibcCoreConnectionV1
  )

  return {
    queryConnection,

    queryConnections,

    queryClientConnections,

    queryConnectionClientState,

    queryConnectionConsensusState
  }
}

export { useModule }
